### ISSUE TITLE
Update Cypress e2e testing to reduce Runtimes

### ISSUE THREAD

**Issue by schen2166** [EasyDynamics/oscal-editor-deployment#108]
The cypress e2e tests are functioning however there are a few tests that have unreasonably long run times. This could possibly be because:
-GitHub Actions can be a slow runner
-our app that slow?
Poorly structured tests
GitHub is slow?

There are also `cy.wait` calls which make the tests longer than needed. Implementing a feature to make the tests run using a timeout feature will optimize the testing environment and make the tests run at better efficiency.

**Comment by tuckerzp** [comment]
Lets hold off on closing this until #113 is fully merged in.
