### ISSUE TITLE
Relative Link Imports Resolving Incorrectly in All-in-One Deployment

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-editor-deployment#128]
### Description

When running the all-in-one deployment with an SSP or Profile that uses a [relative link](https://pages.nist.gov/OSCAL/reference/datatypes/#uri-reference) to import a Catalog/Profile from local files, the link will not be resolved correctly in the OSCAL Editor, so the fetch will fail - meaning no controls are displayed on the page. 
This is necessary to fix as some users will need to view and edit custom controls that are not found online.

### Acceptance Criteria
- An SSP or Profile that imports a Catalog/Profile from other files in the local `oscal-content` directory will correctly display controls from that file when run from the all-in-one deployment image

### Implementation Notes
This seems to be an issue with the configuration of the OSCAL Editor in Spring Boot within the all-in-one deployment.

As an example, a Profile can be loaded that contains an element in its `imports` list that points to a Catalog in `back-matter` with the `rlink` set to `../catalogs/my-catalog.json`. At `oscal-content/catalogs/my-catalog.json` there is a valid OSCAL Catalog with some control.

When running both the REST Service and OSCAL Editor locally (outside of the Docker deployment) the OSCAL Editor makes the fetch as intended. The controls can be viewed, and developer tools shows that the OSCAL Editor makes a fetch request to:
`http://localhost:8080/oscal/v1/catalogs/my-catalog.json`

When running from the all-in-one image, however -
Developer tools shows that the OSCAL Editor makes an invalid fetch request to:
` http://localhost:8080/oscal/v1/profiles//oscal/v1/catalogs/my-catalog.json`
Causing the UI to render:
![image](https://user-images.githubusercontent.com/43356777/182632509-466708b0-6dd6-4b69-a915-ce4f6579ce20.png)

**Comment by naiqbal** [comment]
This issue will be a spike (Research based ticket only). actual fix of the bug will come after the issue and approach is determined.

**Comment by hreineck** [comment]
The discrepancy between the behavior in the Docker deployment and in the example build is due to the `REST_APP_BASE_URL` environment variable being set differently.

The all-in-one Dockerfile sets this variable to `oscal/v1` as shown [here](https://github.com/EasyDynamics/oscal-editor-deployment/blob/main/all-in-one/Dockerfile#L42).

The [README](https://github.com/EasyDynamics/oscal-react-library#experimental-rest-features) for the OSCAL React Library instructs a user to set this variable to `http://localhost:8080/oscal/v1`

These are both correct, because the all-in-one Dockerfile needs to be agnostic of the port that it is running on, so that the user can choose any port they want as they run the container. However, in the case of the all-in-one deployment, it causes an issue with how the OSCAL React Library interprets links that are missing the `http://` prefix.

In the React Library, the environment variable is passed into `OSCALLoader` and used to build the URL for REST requests as shown [here](https://github.com/EasyDynamics/oscal-react-library/blob/develop/src/components/OSCALLoader.js#L69)

This all works as intended and the REST requests are built properly; when a Profile is resolving controls from a local catalog, the URL is passed down as `parentUrl` in `OSCALProfileResolver` which is meant to resolve the relative link.
The issue comes from how the link is interpreted as it passed into `resolveLinkHref` [here](https://github.com/EasyDynamics/oscal-react-library/blob/develop/src/components/oscal-utils/OSCALLinkUtils.js#L18). On line 15, a relative link (ie. one that does not start with "http") is appended onto `parentUrl`. 
We end up with a final link for the fetch request that looks like:
`oscal/v1/catalogs/my-catalog.json`

This link is now still missing the `http://` prefix, so the browser interprets it as a link relative to its current page, resulting in a final request to something screwy like `http://localhost:8080/oscal/v1/profiles//oscal/v1/catalogs/my-catalog.json`

**Comment by hreineck** [comment]
This is now addressed in https://github.com/EasyDynamics/oscal-react-library/pull/571
Once that's merged this can be closed.
