### ISSUE TITLE
Optimize Size of Docker Image

### ISSUE THREAD

**Issue by mikeisen1** [EasyDynamics/oscal-editor-deployment#7]
As a user running the OSCAL Editor all-in-one Docker deployment, I want to consume as small an image as possible so that I can more quickly deploy the app and save space on my machine / Docker registry.

As an IT administrator, I want the OSCAL Editor all-in-one Docker image to be as small as possible so that I can optimize costs.

For the deployment of the OSCAL Editor all-in-one Docker image, we are relying on the use of GitHub Packages, with multiple artifacts being pulled into the Docker image as well as publishing the image to GitHub Packages. We should look into how the size of the image can be reduced to maintain an efficient CI/CD pipeline and cost-optimized use of GitHub Packages.

### Implementation Notes

- We should investigate the base image being used and ensure we're not adding unnecessary artifacts to the image layers

### Acceptance Criteria

 - Either the Docker image has been optimized to result in a smaller sized image at the end of the build process or justification is provided for why that is not feasible
 - Documentation exists for the process used for slimming the image further
 - Metrics are provided for before/after optimization

**Comment by Bronstrom** [comment]
3/10/23 Sprint Planning - Moved from Sprint 42 to Sprint 43
