### ISSUE TITLE
Cannot read properties of undefined (reading 'uuid')

### ISSUE THREAD

**Issue by AdamLeonSmith** [EasyDynamics/oscal-editor-deployment#87]
This project looks great, thanks!

I am using the docker container, which I have started with the recommended directory structure and a single XML file defining a catalog. When I select my catalog, the UI shows:

```
Yikes! Something went wrong loading the OSCAL data.
Cannot read properties of undefined (reading 'uuid')
```

The docker log shows:

`c.e.o.d.r.file.OscalCatalogRepoFileImpl  : Unparsable content found at oscal-content/catalogs/cd2.xml`

It appears that it is unhappy with my uuid.  The relevant snippet of the XML file starts:

```
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns="http://csrc.nist.gov/ns/oscal/1.0"
  uuid="fdaa19ab-f9f2-46ef-8c91-ec6902850a44">
  <metadata>
....
</catalog>
```

Any clues?

Thanks

**Comment by rgauss** [comment]
Hi @AdamLeonSmith, only JSON files are supported at the moment.

We'll update the documentation to make that more clear.

**Comment by AdamLeonSmith** [comment]
Aha. OK thanks!

**Comment by rgauss** [comment]
#88 should improve documentation around this.

@AdamLeonSmith, thanks for raising the issue!
