### ISSUE TITLE
Subtask: End-to-End test using `Object Selector` component

### ISSUE THREAD

**Issue by mikeisen1** [EasyDynamics/oscal-editor-deployment#98]
### Acceptance Criteria 
- Test loading via `uuid` in the address bar to navigate to an example `SSP`, `Catalog`, `Profile`, & `Component Definition`. 
- Test loading those same examples by using the `Drawer Selector`
  - `url` should also update to reflect the loaded object's `uuid`
  - Test that multiple of an `oscal object` are properly listed. For example, multiple `catalogs`. This may require adding some more example data. 
- Ensure that removing the `LoaderForm` while in `REST` mode, does not break functionality of tests.

**Comment by tuckerzp** [comment]
https://github.com/EasyDynamics/oscal-demo-content/pull/18 will provide another `profile` & another `component` to load.
